### ISSUE TITLE
Please add readme and source

### ISSUE THREAD

**Issue by rfay** [ddev/test-cakephp#1]
The idea of this repo is that we should be able to update the actual source that the tarball is built from at any time to update it. So it needs at least
- [x] Source code
- [x] README that explains how to create updated artifacts for tests

Thanks!

**Comment by ajibarra** [comment]
To be able to update project easily you need to create this repo as a fork of https://github.com/cakephp/app. I am sorry about the confusion.

**Comment by rfay** [comment]
The idea is that this repo needs to contain full contents and instructions to be able to recreate the artifacts. In other words, the artifacts you're using in the release should be recreatable from the contents of this repo. It's fine for it to be a fork with additional information.  Thank you!

**Comment by ajibarra** [comment]
Updated! Please check and close if everything is ok

**Comment by rfay** [comment]
Thanks, perfect, closing, but please add at least one more bullet point explaining how to create the artifacts and put them into a release (or have you automated that?)

**Comment by ajibarra** [comment]
I added a couple of bullets to readme..I diddnt create a new release becausee I dont think is necessary for this change.

**Comment by rfay** [comment]
Don't you need a tarball of user-generated files? (I like the fact that you're using the actual release tarball)
